apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-microservice
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-microservice
  template:
    metadata:
      labels:
        app: my-microservice
    spec:
      containers:
        - name: my-microservice
          image: florinelfrancisc/my-microservice:1.0.0
          ports:
            - containerPort: 8086
          env:
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: my-microservice-config
                  key: WELCOME_MSG
            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-microservice-secret
                  key: SECRET_TOKEN
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /
              port: 8086
          readinessProbe:
            httpGet:
              path: /
              port: 8086
      ports:
        - name: http
          port: 80
          targetPort: 8086