apiVersion: v1
kind: Service
metadata:
  name: my-microservice
  namespace: microservices
spec:
  selector:
    app: my-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
  type: NodePort